export const MUTATION_SUBSCRIBE_EMPLOYEES = 'MUTATION_SUBSCRIBE_EMPLOYEES';
export const MUTATION_UNSUBSCRIBE_EMPLOYEES = 'MUTATION_UNSUBSCRIBE_EMPLOYEES';
export const MUTATION_SET_EMPLOYEES = 'MUTATION_SET_EMPLOYEES';
export const MUTATION_CREATE_EMPLOYEE = 'MUTATION_CREATE_EMPLOYEE';
export const MUTATION_DELETE_EMPLOYEES = 'MUTATION_DELETE_EMPLOYEES';
export const MUTATION_ADD_MEASURE_RATE = 'MUTATION_ADD_MEASURE_RATE';
export const MUTATION_CHANGE_MEASURE_RATE = 'MUTATION_CHANGE_MEASURE_RATE';
