export const MUTATION_SET_EMPLOYEES = 'MUTATION_SET_EMPLOYEES';
export const MUTATION_CREATE_EMPLOYEE = 'MUTATION_CREATE_EMPLOYEE';
export const MUTATION_DELETE_EMPLOYEES = 'MUTATION_DELETE_EMPLOYEES';
export const MUTATION_ADD_MEASURE_RATE = 'MUTATION_ADD_MEASURE_RATE';
export const MUTATION_CHANGE_MEASURE_RATE = 'MUTATION_CHANGE_MEASURE_RATE';

export const MUTATION_SET_MEASURES = 'MUTATION_SET_MEASURES';
export const MUTATION_CREATE_MEASURE = 'MUTATION_CREATE_MEASURE';
export const MUTATION_DELETE_MEASURES = 'MUTATION_DELETE_MEASURES';
