export const MUTATION_SET_EMPLOYEES = 'MUTATION_SET_EMPLOYEES';
export const MUTATION_CREATE_EMPLOYEE = 'MUTATION_CREATE_EMPLOYEE';
export const MUTATION_DELETE_EMPLOYEES = 'MUTATION_DELETE_EMPLOYEES';
