export const MUTATION_SUBSCRIBE_MODULE = 'MUTATION_SUBSCRIBE_MODULE';
export const MUTATION_UNSUBSCRIBE_MODULE = 'MUTATION_UNSUBSCRIBE_MODULE';

export const MUTATION_SET_USER = 'MUTATION_SET_USER';
export const MUTATION_UNSET_USER = 'MUTATION_UNSET_USER';

export const MUTATION_TOGGLE_MENU = 'MUTATION_TOGGLE_MENU';
export const MUTATION_OPEN_CONTEXT_MENU = 'MUTATION_OPEN_CONTEXT_MENU';
export const MUTATION_CLOSE_CONTEXT_MENU = 'MUTATION_CLOSE_CONTEXT_MENU';
export const MUTATION_SHOW_MESSAGE = 'MUTATION_SHOW_MESSAGE';
export const MUTATION_HIDE_MESSAGE = 'MUTATION_HIDE_MESSAGE';
export const MUTATION_SHOW_MODAL = 'MUTATION_SHOW_MODAL';
export const MUTATION_HIDE_MODAL = 'MUTATION_HIDE_MODAL';

export const MUTATION_INIT_EMPLOYEES_DELETION = 'MUTATION_INIT_EMPLOYEES_DELETION';
export const MUTATION_CANCEL_EMPLOYEES_DELETION = 'MUTATION_CANCEL_EMPLOYEES_DELETION';
export const MUTATION_TOGGLE_EMPLOYEE_DELETION = 'MUTATION_TOGGLE_EMPLOYEE_DELETION';
