export const MUTATION_SET_USER = 'MUTATION_SET_USER';

export const MUTATION_UNSET_USER = 'MUTATION_UNSET_USER';

export const MUTATION_SET_EMPLOYEES = 'MUTATION_SET_EMPLOYEES';

export const MUTATION_TOGGLE_MENU = 'MUTATION_TOGGLE_MENU';

export const MUTATION_OPEN_CONTEXT_MENU = 'MUTATION_OPEN_CONTEXT_MENU';

export const MUTATION_CLOSE_CONTEXT_MENU = 'MUTATION_CLOSE_CONTEXT_MENU';

export const MUTATION_SHOW_MESSAGE = 'MUTATION_SHOW_MESSAGE';

export const MUTATION_HIDE_MESSAGE = 'MUTATION_HIDE_MESSAGE';

export const MUTATION_SHOW_MODAL = 'MUTATION_SHOW_MODAL';

export const MUTATION_HIDE_MODAL = 'MUTATION_HIDE_MODAL';

export const MUTATION_ADD_SKILL_RATE = 'MUTATION_ADD_SKILL_RATE';

export const MUTATION_CHANGE_SKILL_RATE = 'MUTATION_CHANGE_SKILL_RATE';

export const MUTATION_ADD_EMPLOYEE = 'MUTATION_ADD_EMPLOYEE';

export const MUTATION_INIT_EMPLOYEES_DELETION = 'MUTATION_INIT_EMPLOYEES_DELETION';

export const MUTATION_CANCEL_EMPLOYEES_DELETION = 'MUTATION_CANCEL_EMPLOYEES_DELETION';

export const MUTATION_TOGGLE_EMPLOYEE_DELETION = 'MUTATION_TOGGLE_EMPLOYEE_DELETION';

export const MUTATION_DELETE_EMPLOYEES = 'MUTATION_DELETE_EMPLOYEES';

export const MUTATION_SET_METRICS = 'MUTATION_SET_METRICS';

export const MUTATION_CREATE_METRICS = 'MUTATION_CREATE_METRICS';

export const MUTATION_DELETE_METRICS = 'MUTATION_DELETE_METRICS';
