export const MUTATION_SET_USER = 'MUTATION_SET_USER';

export const MUTATION_UNSET_USER = 'MUTATION_UNSET_USER';

export const MUTATION_SET_EMPLOYEES = 'MUTATION_SET_EMPLOYEES';

export const MUTATION_TOGGLE_MENU = 'MUTATION_TOGGLE_MENU';

export const MUTATION_OPEN_CONTEXT_MENU = 'MUTATION_OPEN_CONTEXT_MENU';

export const MUTATION_CLOSE_CONTEXT_MENU = 'MUTATION_CLOSE_CONTEXT_MENU';

export const MUTATION_SHOW_MESSAGE = 'MUTATION_SHOW_MESSAGE';

export const MUTATION_HIDE_MESSAGE = 'MUTATION_HIDE_MESSAGE';

export const MUTATION_ADD_SKILL_RATE = 'MUTATION_ADD_SKILL_RATE';

export const MUTATION_CHANGE_SKILL_RATE = 'MUTATION_CHANGE_SKILL_RATE';
